name: "Helm deploy Action"
description: "GitHub Action to install/upgrade services using Helm"
inputs:
  deploy_mode:
    description: |
      Deployment mode:
      - 'install' for clean installation
      - 'update' to upgrade an existing release
    required: true
    default: 'install'

  restricted:
    description: |
      - 'true': helm installation by user with restricted rights
      - 'false': helm installation by cluster admin user
    required: true
    default: 'false'
    type: boolean

  path_to_template:
    description: |
      Path to template file in qubership-test-pipelines repository
      Example: 'templates/consul-service/consul_clean_infra_passport.yml'
    required: true

  service_branch:
    description: |
      Branch in service repository
    required: true

  service_name:
    description: |
      Helm release name
    required: true

  repository_name:
    description: |
      Service repository name (without organization prefix)
      Example: 'qubership-consul' for https://github.com/Netcracker/qubership-consul
    required: true

  path_to_chart:
    description: |
      Path to helm chart within service repository
      Example: 'charts/helm/consul-service'
    required: true

  namespace:
    description: |
      Kubernetes namespace for service installation
    required: true

  helm_charts_release_config:
    description: |
      Path to helm-charts-release-config.yaml in pipeline repository
    required: false

  resource_folder:
    description: |
      Folder with resources for creating before installation
    required: true

  docker_tag:
    description: "Full docker image"
    required: false

  postgres:
    description: "Postgres installation"
    required: false
    default: 'disable'

  mongo:
    description: "Mongo installation"
    required: false
    default: 'disable'

  kafka:
    description: "Kafka installation"
    required: false
    default: 'disable'

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: '${{inputs.service_branch}}'
        repository: 'Netcracker/${{inputs.repository_name}}'
        path: '${{inputs.repository_name}}'

    - name: Create namespace
      if: inputs.deploy_mode == 'install'
      shell: bash
      # language=bash
      run: |
        if ! kubectl get namespace ${{inputs.namespace}} >/dev/null 2>&1; then
        kubectl create namespace ${{inputs.namespace}}
        else
        echo "Namespace '${{inputs.namespace}}' already exists"
        fi
        kubectl config set-context --current --namespace=${{inputs.namespace}}

    - name: Create resources
      if: inputs.resource_folder != ''
      shell: bash
      # language=bash
      run: |
        folder="${{inputs.resource_folder}}"
        files=($(find "$folder" -type f))
        echo $files
        for file in "${files[@]}"; do
          echo "Applying $file"
          kubectl create -f "$file"
        done

    - name: Name template
      shell: bash
      # language=bash
      run: |
        echo ${{inputs.path_to_template}}
        cp ${{inputs.path_to_template}} ${{inputs.repository_name}}/${{inputs.path_to_chart}}
        ls -la

    - name: Replace slash in service branch
      id: replace_slash
      shell: bash
      # language=bash
      run: |
        service_branch="${{inputs.service_branch}}"
        if [[ "${service_branch}" == *"/"* ]]; then
          service_branch_updated=$(echo "${service_branch}" | tr '/' '_')
        else
          service_branch_updated=${service_branch}
        fi
        echo ${service_branch_updated}
        echo "service_branch_updated=${service_branch_updated}" >> $GITHUB_OUTPUT

    - name: Initialize error flag
      shell: bash
      # language=bash
      run: echo "ERROR_FLAG=false" >> $GITHUB_ENV

    - name: Set DOCKER_TAG
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          BRANCH_NAME="${{ inputs.service_branch }}"
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BRANCH_NAME="${{ github.head_ref }}"
        else
          BRANCH_NAME="${{ github.ref_name }}"
        fi

        if [[ "$BRANCH_NAME" == "main" ]]; then
          echo "DOCKER_TAG=ghcr.io/netcracker/${{ inputs.repository_name }}:main_latest" >> $GITHUB_ENV
        else
          echo "DOCKER_TAG=ghcr.io/netcracker/${{ inputs.repository_name }}:${BRANCH_NAME}_latest" >> $GITHUB_ENV
        fi

    - name: Install Postgres
      if: ${{ inputs.postgres == 'enable' }}
      shell: bash
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami

        helm install my-postgres bitnami/postgresql \
          --set image.registry=docker.io \
          --set image.repository=bitnamilegacy/postgresql \
          --set image.tag=14.2.0 \
          --set auth.username=postgres \
          --set auth.password=postgrestest \
          --set auth.database=postgres

        pod=$(kubectl get pods -o name | head -n 1 | cut -d/ -f2)
        kubectl wait pod "$pod" \
          --for=condition=Ready \
          --timeout=120s || {
          echo "❌ Pod $pod did not become ready in time"
          ERROR_FLAG=true
          exit 1
        }

    - name: Install MongoDB via bitnami
      if: ${{ inputs.mongo == 'enable' }}
      shell: bash
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami

        helm install my-mongodb bitnami/mongodb \
          --set image.registry=docker.io \
          --set image.repository=bitnamilegacy/mongodb \
          --set image.tag=8.0.13 \
          --set auth.rootUser=root \
          --set auth.rootPassword=root

        pod=$(kubectl get pods -o name | grep -vE 'postgres' | head -n 1 | cut -d/ -f2)
        kubectl wait pod "$pod" \
           --for=condition=Ready \
           --timeout=120s || {
           echo "❌ Pod $pod did not become ready in time"
           ERROR_FLAG=true
           exit 1
        }

    - name: Install Kafka via bitnami
      if: ${{ inputs.kafka == 'enable' }}
      shell: bash
      run: |
        cd qubership-testing-platform-helm-hook-helper/.github/templates/
        ls -la
        helm repo add bitnami https://charts.bitnami.com/bitnami

        helm install kafka bitnami/kafka \
          --version 25.0.0 \
          --create-namespace \
          -f no-auth-values.yaml

        pod=$(kubectl get pods -o name | grep -vE 'postgres|mongodb' | head -n 1 | cut -d/ -f2)
        kubectl wait pod "$pod" \
           --for=condition=Ready \
           --timeout=300s || {
           echo "❌ Pod $pod did not become ready in time"
           ERROR_FLAG=true
           exit 1
        }

    - name: Install/update service with helm
      shell: bash
      run: |
        # ▶️ ${{inputs.deploy_mode}} with Helm
        template_name=$(basename "${{inputs.path_to_template}}")
        echo $template_name

        if [ "${{ inputs.apply_kube2vcs }}" = "enable" ]; then
          cd qubership-testing-platform-helm-hook-helper/.github/templates/
          kubectl apply -f kube2vcs.yaml
          cd ../../..
          cd ${{inputs.repository_name}}/${{inputs.path_to_chart}}
        else
          cd ${{inputs.repository_name}}/${{inputs.path_to_chart}}
        fi

        set +e
        if [ -n "${{ env.DOCKER_TAG }}" ]; then
          echo "Using docker_tag: ${{ env.DOCKER_TAG }}"
          helm ${{inputs.deploy_mode}} ${{inputs.service_name}} . -f $template_name --set-string DOCKER_TAG=${{ env.DOCKER_TAG }}
        else
         echo "No DOCKER_TAG provided."
         helm ${{inputs.deploy_mode}} ${{inputs.service_name}} . -f $template_name
        fi
        HELM_EXIT_CODE=$?
        set -e

        if [ $HELM_EXIT_CODE -ne 0 ]; then
          echo "❌ Helm install failed"
          echo "Waiting for predeploy pod..."
          kubectl wait --for=condition=ready pod -l job-name=${{inputs.service_name}}-predeploy-install \
            --timeout=60s || true

          echo "Get logs for predeploy-install"
          kubectl logs $(kubectl get pods --selector=job-name=${{inputs.service_name}}-predeploy-install \
            -o jsonpath='{.items[0].metadata.name}')
          echo "End logs"
        fi

        pod=$(kubectl get pods -o name | grep -vE 'postgres|mongodb|kafka|predeploy|activemq' | head -n 1 | cut -d/ -f2)
        kubectl wait pod "$pod" \
           --for=condition=Ready \
           --timeout=600s || {
           echo "❌ Pod $pod did not become ready in time"
           ERROR_FLAG=true
        }

    - name: Get docker images
      shell: bash
      # language=bash
      run: |
        # ▶️ Get docker images
        kubectl get pods -o go-template --template="{{range .items}}{{range .spec.containers}}{{.image}} {{end}}{{end}}"
